version: "3.3"
services:
  node:
    container_name: shippifyChallenge
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mariadb
    volumes:
      - .:/usr/src/app
  mariadb:
    container_name: mariadbShippifyChallenge
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shippifyChallengeDB
      MARIADB_USER: shippifyChallengeUser
      MARIADB_PASSWORD: shippifyChallengePass
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
